site_name: offchain
repo_url: https://github.com/ourzora/offchain
repo_name: ourzora/offchain
nav:
  - Getting Started: index.md
  - Core Concepts: concepts.md
  - Usage:
      - Overview: usage/overview.md
      - Customizing the Pipeline: usage/customize.md
  - Interfaces:
      - Token: models/token.md
      - Metadata: models/metadata.md
      - MetadataProcessingError: models/metadata_processing_error.md
  - Pipeline:
      - Pipeline: pipeline/pipeline.md
      - Adapters: pipeline/adapters.md
      - Fetchers: pipeline/fetchers.md
      - Parsers: pipeline/parsers.md
  - Contributing:
      - Guidelines: contributing/guidelines.md
      - Collection Parser: contributing/collection_parser.md
      - Schema Parser: contributing/schema_parser.md
      - Adapter: contributing/adapter.md
  - Changelog: changelog.md
theme:
  name: material
  font:
    text: Roboto Mono
  palette:
    # Palette toggle for dark mode
    - scheme: slate
      primary: black
      toggle:
        icon: material/weather-night
        name: Switch to light mode
    # Palette toggle for light mode
    - scheme: default
      primary: black
      toggle:
        icon: material/weather-sunny
        name: Switch to dark mode
  logo: assets/zorb.png
  favicon: assets/zorb.png
plugins:
  - search
  - mkdocstrings:
      custom_templates: templates
      default_handler: python
      handlers:
        python:
          options:
            show_source: true
            show_root_heading: false
            show_root_toc_entry: false
            show_bases: false
            heading_level: 3
markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
