name: Publish Offchain

on:
  release:
    types: [created]

jobs:
  deploy:
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2

      - name: Install Poetry
        uses: snok/install-poetry@v1

      - run: poetry config repositories.testpypi https://test.pypi.org/legacy/
      - run: poetry config pypi-token.testpypi ${{ secrets.PYPI_API_KEY }}

      - name: Publish package
        run: poetry publish --build -r testpypi
